### ISSUE TITLE
Feature Request - retry failed/declined transactions

### ISSUE THREAD

**Issue by ncovercash** [bizswoop/Point-of-Sale-POS-WooCommerce#10]
Currently, failed/declined transactions are marked as failed and, to allow the customer to try with a new card, it takes many clicks to get to the order in WooCommerce and, from there, the main checkout page has to be used, rather than the PoS.  This is quite difficult/annoying, especially if a customer comes with a card that is declined or something.

**Comment by SupportBizSwoop** [comment]
Thanks for reaching out and sharing the user experience for the failed/declined transaction. 

We wanted to share the recommended workflow failed/declined transactions you can use with the POS.

Here is a quick video:
https://www.loom.com/share/0207ac94ea9145ab812749355b1001c9

This workflow will allow you to reopen the order and process again in the POS by switching the Order Status back to Pending Payment. 

We are continually reviewing the workflows and hope to enable this process end to end within the POS in the future without the requirement to access the WooCommerce order details page.

**Comment by ncovercash** [comment]
Thanks for the feedback.
