### ISSUE TITLE
is it possible to have variations in a single product?

### ISSUE THREAD

**Issue by HamzaDams** [bizswoop/Point-of-Sale-POS-WooCommerce#4]
is it possible to have variations in a single product?

**Comment by HamzaDams** [comment]
https://prnt.sc/r1wkp5

**Comment by corycpf** [comment]
Good question. 

The default functionality of WooCommerce doesn't support variations in a single product. 

As a result, we developed a plugin app to support variations in a single product. 

The Product Add-ons plugin app:
https://wordpress.org/plugins/product-add-ons-woocommerce/

This plugin is compatible with the Point of Sale plugin app. The Product Add-ons will show similar to your screenshot in the POS. 

When you click the single product, a new view will show allowing you to select Add-ons for the single product. This Product Add-ons functionality for the POS is used a lot in restaurant food businesses to customize the product.  

![Add-ons](https://user-images.githubusercontent.com/7434668/74461165-16851680-4e5c-11ea-9027-e370082e98ad.png)

**Comment by HamzaDams** [comment]
I do not understand how your plugins work I would like to know if you have a video of explanation or demonstration of car

**Comment by SupportBizSwoop** [comment]
@HamzaDams 

I'm happy to provide additional information to explain the functionality of Product Add-ons plugin app and the POS plugin app. 

As we mentioned earlier, the default functionality of WooCommerce doesn't support variations in a single product. As a result, we developed a companion plugin to enable this functionality with the Product Add-ons plugin app:
https://wordpress.org/plugins/product-add-ons-woocommerce/

After the Product Add-ons plugin is installed and activated, you can now create add-ons and map them to **all products** or **select products** or **select categories.**

In this example video, we show setting Product Add-ons for a Product: Demo
https://www.loom.com/share/be2c9477436d4d4eab9765a03c253af5

You can see we setup Product Add-ons, we selected the Custom option to apply the Product Add-ons for the Demo product. Now, on the Demo product you will have two Product Add-ons: Protein and Drink

Now launch the POS, if you select the Demo product, you will see the two Product Add-ons:

Here is a video showing the behavior of the Product Add-ons and Cart functionality:
https://www.loom.com/share/f061677a14954df28618f3921f6ed1be

If you are using the Product Add-ons plugin app now and the changes are not showing in the POS, we also recommend a quick Force Sync of the POS, this will force an update for the latest settings and product modifications.

Here is a quick video to show how to force sync settings in the POS:
https://www.loom.com/share/19f51576750146de8c10cf66b078ef42

From these videos and information, we have shown how Product Add-ons can be setup on a Product. You can also setup Product Add-ons to show on All products in the Store or also setup Product Add-ons to show on specific Categories. 

We'd also recommend you test the functionality on our demo site of Product Add-ons and the POS, here is our Demo site: https://bizswooptech.com/.  You can test and try the full functionality to evaluate if you'd like to use the plugin for your website.

I hope that information helps to explain the Product Add-ons plugin app product and POS plugin app.

**Comment by HamzaDams** [comment]
It doesn't work i understand

**Comment by SupportBizSwoop** [comment]
@HamzaDams 

Sorry I don't understand. Can you clarify?

Did the functionality not work? or

Did this type of functionality not work for your business use case?

We'd love to understand more about why it didn't work for you. If there is a bug, we will review and fix. If there is a bug, can you provide specific details on what didn't work. This will help us try and reproduce the bug.  

Or if you have a difference business requirement, let us know the details to understand if we can add this functionality in the future.

**Comment by HamzaDams** [comment]
https://prnt.sc/r4qjcq

https://prnt.sc/r4qjp8
https://prnt.sc/r4qjzj
https://prnt.sc/r4qk7c
https://prnt.sc/r4ql0m

Sorry if I do not give details but it is that I do not understand why it does not work :)

**Comment by SupportBizSwoop** [comment]
@HamzaDams Thank you for the screenshots, this was very helpful.

Let's try to delete the data on your POS and do a Force Sync as shown in this video:
https://www.loom.com/share/6732c252c3e84c98ace210a2bcfe417f

For speed and performance, the POS will store data in the browser. If you make changes, like adding products or product add-ons, sometimes it's good to clear the data and force a new sync event. This will make sure the latest changes are showing in the POS. 

Give the Clear Data and Force Sync a try, this should fix the product and start showing the product add-ons.
