### ISSUE TITLE
Syntax Error in WooPOS e-commerce

### ISSUE THREAD

**Issue by ClementinaAlbacete** [bizswoop/Point-of-Sale-POS-WooCommerce#8]
Hi, I got a syntax error when I click in some buttons of the plugin (print principally). The text: Unexpected token < in JSON at position 0 appears. I don´t understand the problem. If u can help me pls... Cheers. Thanks u.

**Comment by SupportBizSwoop** [comment]
We'd be happy to help support. 

The first thing we want to determine is if any other plugins are creating a conflict with the POS plugin. Could you please perform our Plugin/Theme testing to verify if any other plugins are creating the resulting error

Plugin/Theme testing guide:
https://www.bizswoop.com/plugin-theme-conflict-test/

The testing is quick and easy, deactivate all plugins except WooCommerce and the POS plugin. Does the error still occur? If no, one-by-one activate a plugin and verify when the conflict occurs. Once you identify the plugin, or conflict, please share and report to us, so we can review and evaluate. 

In the next 24 hours, we are releasing a new update **_version 2.1.1_**, we'd recommend you upgrade to this version and perform the testing we describe. If after the upgrade and the plugin theme testing the errors are still occurring, we'd like to review your error logs. 

To avoid submitting logs in the public forum, we'd recommend you use our official support channel at bizswoop.com/support

We'd need the following logs to review the cause of the error:

**General PHP Logs from WordPress**

Stored normally in the FTP directory: wp-content/debug.log

Note: If you are unfamiliar with debug logs for WordPress, a lot of hosting providers will provide them to you. Reach out to your hosting provider and ask for PHP debug logs for WordPress. 

**WooCommerce System Logs**

To get this log. Click WooCommerce. Click System. Click Get System Report, copy the log and send it to us as a text file.

**WooCommerce Error Logs**

Stored wp-admin/admin.php?page=wc-status&tab=logs, on your admin for WooCommerce. To find them. Click WooCommerce, Click Status. Click Logs. In the Drop Down. You will need to look for any fatal errors that contain zPOS. We’d only want to see those logs related to the POS.

Please send us those 3 log types: **PHP Debug Logs**, **WooCommerce System Logs** and **any WooCommerce Error Logs linked to zPOS**.

Hopefully this upcoming version 2.1.1 and the plugin conflict testing will resolve the error and allow you to enjoy the POS plugin app. If not, please reopen the issue and report the logs to our official channel for our QA and Development to review.
